### PR TITLE
CONFIG: SETI-4077 remove obsoletes package in spec file

### PR DESCRIPTION
**Pull request by tvhien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/13/ : FAILURE in 9m 03s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/8/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/14/ : ABORTED in 1h 00m 00s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/9/ : SUCCESS in 4s

**Comment by chiendm** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/15/ : ABORTED in 1h 00m 00s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/10/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/17/ : SUCCESS in 7m 42s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-merge-compliance-check/2/ : SUCCESS in 19s

**Pull request merged**
