### PR TITLE
CONFIG: SETI-4077 add build-flow-plugin.spec and Makefile

### PR DESCRIPTION
**Pull request by tvhien**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/1/ : ABORTED in 1h 00m 00s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/1/ : SUCCESS in 3s

**Comment by tvhien** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/2/ : ABORTED in 1h 00m 00s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/2/ : SUCCESS in 3s

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/3/ : ABORTED in 33m 58s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/3/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/8/ : SUCCESS in 9m 23s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/4/ : SUCCESS in 16s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/10/ : ABORTED in 1h 00m 00s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/6/ : SUCCESS in 3s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/11/ : FAILURE in 8m 47s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-oss-check/7/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/java-libraries/job/build-flow-plugin-tests-zuul-el7/12/ : SUCCESS in 8m 05s
- https://checklist.intgdc.com/job/compliance/job/build-flow-plugin-merge-compliance-check/1/ : SUCCESS in 19s

**Pull request merged**
